### ISSUE TITLE
Request: Module to set downtime for a server

### ISSUE THREAD

**Issue by kasimon** [tribe29/ansible-checkmk#19]
In order to automate the update+reboot process of a server, it would be extremely helpful if there was a ansible module to set and remove the downtime setting for a server or a service.

**Comment by robin-checkmk** [comment]
Hi @kasimon! We are actually currently working on our very own official [Ansible Collection](https://github.com/tribe29/ansible-collection-tribe29.checkmk). There is no official roadmap, as it is a side project, but downtimes will probably be in the not too distant future. Please open an issue over there, so we can track the request there.
Thanks!

**Comment by kasimon** [comment]
I'll do, thanks!

**Comment by robin-checkmk** [comment]
In case someone stumbles upon this: https://github.com/tribe29/ansible-collection-tribe29.checkmk/issues/19
