### ISSUE TITLE
checkmk_services not working

### ISSUE THREAD

**Issue by eschek87** [tribe29/ansible-checkmk#20]
- name: Adds new and removes vanished services
  checkmk_services:
    url: "{{ cmk_site_url }}"
    user: "{{ cmk_site_user }}"
    password: "{{ cmk_site_password }}"
    name: "{{ inventory_hostname }}"
    mode: fixall
    validate_certs: false

"msg": "value of mode must be one of: , got: fixall"

- name: Adds new and removes vanished services
  checkmk_services:
    url: "{{ cmk_site_url }}"
    user: "{{ cmk_site_user }}"
    password: "{{ cmk_site_password }}"
    name: "{{ inventory_hostname }}"
    validate_certs: false

"msg": "value of mode must be one of: , got: new"

**Comment by robin-checkmk** [comment]
@eschek87 head over to [our official Ansible collection](https://github.com/tribe29/ansible-collection-tribe29.checkmk) the functionality is there and should do, what you are looking for.
