### ISSUE TITLE
Question about TLS CA in conjunction with Ansible Tower

### ISSUE THREAD

**Issue by FleischKarussel** [tribe29/ansible-checkmk#3]
Hello everyone,

I am having some issues getting the roles running in an AWX/Tower environment.
I'm not being used to python in general but curious why this role is not able to find the self-signed CA but other modules and roles are working just fine also relying on the same CA.
It's more a less a question, where does it look for like bundled file or directory with cert files?
What I found out so far is just pinpointing to the requests module, which every ansible module with http(s) connetions is using.

Specs:
Ubuntu 16.04
Tower 3.5.2
Ansible 2.8.6
self-signed CA cert successfully registered with update-ca-certificates

This is the message I get when running the registration role against our checkmk server in ansible debug level 3.

>"module_stderr": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1571995182.0-32966893302187/AnsiballZ_checkmk_host.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1571995182.0-32966893302187/AnsiballZ_checkmk_host.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1571995182.0-32966893302187/AnsiballZ_checkmk_host.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_checkmk_host_payload_5jpPJJ/__main__.py\", line 252, in <module>\n  File \"/tmp/ansible_checkmk_host_payload_5jpPJJ/__main__.py\", line 193, in main\n  File \"/tmp/ansible_checkmk_host_payload_5jpPJJ/__main__.py\", line 99, in __init__\n  File \"/tmp/ansible_checkmk_host_payload_5jpPJJ/__main__.py\", line 103, in _get\n  File \"/tmp/ansible_checkmk_host_payload_5jpPJJ/ansible_checkmk_host_payload.zip/ansible/module_utils/checkmk_api.py\", line 79, in _decorator\n  File \"/tmp/ansible_checkmk_host_payload_5jpPJJ/ansible_checkmk_host_payload.zip/ansible/module_utils/checkmk_api.py\", line 85, in get\n  File \"/tmp/ansible_checkmk_host_payload_5jpPJJ/ansible_checkmk_host_payload.zip/ansible/module_utils/checkmk_api.py\", line 30, in query\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/requests/api.py\", line 75, in get\n    return request('get', url, params=params, **kwargs)\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/requests/api.py\", line 60, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/requests/sessions.py\", line 524, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/requests/sessions.py\", line 637, in send\n    r = adapter.send(request, **kwargs)\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/requests/adapters.py\", line 416, in send\n    self.cert_verify(conn, request.url, verify, cert)\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/requests/adapters.py\", **line 228, in cert_verify\n    \"invalid path: {}\".format(cert_loc))\nIOError: Could not find a suitable TLS CA certificate bundle, invalid path: yes\n",**
    "changed": false,
    "module_stdout": "",
    "rc": 1,
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
}

**Comment by marcogabriel** [comment]
The same problem applies if the check_mk server uses a LetsEncrypt certificate. 

Setting the recommended environment variable to REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt doesn't change anything.

**Comment by godspeed-you** [comment]
Hi,
as mentioned before, this problem is most likely related to requests using it's own ca-certificate bundle. If you want to overwrite that with the hint (export REQUESTS_CA_BUNDLE) you need to take care, that this is done for the correct user, that executes the playbook.
