### ISSUE TITLE
The error was: AttributeError: 'Changes' object has no attribute 'hostname'

### ISSUE THREAD

**Issue by Nosreme1** [tribe29/ansible-checkmk#4]
Hello everybody,
I am trying to use the role "cmk_host_registration" but I have the following error: " The error was: AttributeError: 'Changes' object has no attribute 'hostname' ".
Could anyone help me please ?
Thanks in advance.

**Comment by pradeeshg10** [comment]
Yes, I have same issue. do  you have solution for this issue.

Thanks

**Comment by liszca** [comment]
Me too! But host can be found in inventory and after changing Activate default to "yes" it kind of works.
