### ISSUE TITLE
SSLError Error using cmk_host_registration role

### ISSUE THREAD

**Issue by m3rlinux** [tribe29/ansible-checkmk#5]
Hello everybody,
I am trying to use the role "cmk_host_registration" but I have the following error: " An exception occurred during task execution. To see the full traceback, use -vvv. The error was: requests.exceptions.SSLError: [Errno 2] No such file or directory
fatal: [demo-apife01 -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1592741294.94-17354-203445119951044/AnsiballZ_checkmk_host.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1592741294.94-17354-203445119951044/AnsiballZ_checkmk_host.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1592741294.94-17354-203445119951044/AnsiballZ_checkmk_host.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.checkmk_host', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_checkmk_host_payload_IKO4aY/ansible_checkmk_host_payload.zip/ansible/modules/checkmk_host.py\", line 252, in <module>\n  File \"/tmp/ansible_checkmk_host_payload_IKO4aY/ansible_checkmk_host_payload.zip/ansible/modules/checkmk_host.py\", line 193, in main\n  File \"/tmp/ansible_checkmk_host_payload_IKO4aY/ansible_checkmk_host_payload.zip/ansible/modules/checkmk_host.py\", line 99, in __init__\n  File \"/tmp/ansible_checkmk_host_payload_IKO4aY/ansible_checkmk_host_payload.zip/ansible/modules/checkmk_host.py\", line 103, in _get\n  File \"/tmp/ansible_checkmk_host_payload_IKO4aY/ansible_checkmk_host_payload.zip/ansible/module_utils/checkmk_api.py\", line 79, in _decorator\n  File \"/tmp/ansible_checkmk_host_payload_IKO4aY/ansible_checkmk_host_payload.zip/ansible/module_utils/checkmk_api.py\", line 85, in get\n  File \"/tmp/ansible_checkmk_host_payload_IKO4aY/ansible_checkmk_host_payload.zip/ansible/module_utils/checkmk_api.py\", line 30, in query\n  File \"/usr/lib/python2.7/site-packages/requests/api.py\", line 68, in get\n    return request('get', url, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/requests/api.py\", line 50, in request\n    response = session.request(method=method, url=url, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/requests/sessions.py\", line 486, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/lib/python2.7/site-packages/requests/sessions.py\", line 598, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/requests/adapters.py\", line 431, in send\n    raise SSLError(e, request=request)\nrequests.exceptions.SSLError: [Errno 2] No such file or directory\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1} ".
Could anyone help me please ?
Thanks in advance.

**Comment by cstegm** [comment]
Hey, i get the same error.

**Comment by godspeed-you** [comment]
Please check again as soon as the PR of @FloMiau has been merged.

**Comment by godspeed-you** [comment]
As the PR has eventually been merged: Can you confirm, if the problem has been solved?

**Comment by robin-checkmk** [comment]
Closing this issue as resolved because we did not receive disagreeing information.
If you are encountering this error, please open a new issue with reference to this one.
