### ISSUE TITLE
move modules to ansible-collections/community.general 

### ISSUE THREAD

**Issue by keilr** [tribe29/ansible-checkmk#7]
Please move the checkmk ansible modules to the Ansible Collection `community.general`:
https://github.com/ansible-collections/community.general/tree/main/plugins/modules/monitoring

Advantage: Modules will be shipped with ansible und will be updated on a regular basis.

**Comment by godspeed-you** [comment]
Hi @keilr,

this has been the original intention. But as it goes, this project need some more improvement for being shipped with Ansible. Mainly regarding the API integration.
